addons:
  apt:
    packages:
      - xvfb
language: node_js
node_js:
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10

before_install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
